export const ZOOM_IMAGE_ACTION = 'ZOOM_IMAGE_ACTION';
export const HIDE_IMAGE = 'HIDE_IMAGE';
export const FETCH_TIMELINE = 'FETCH_TIMELINE';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK';
export const FETCH_GALLERY = 'FETCH_GALLERY';
export const SET_CURRENT_IMG = 'SET_CURRENT_IMG';
